image: gcc:latest

stages:
  - build
  - test

job_build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

job_test:
  stage: test
  script:
    - cd build
    - ./tests
