image: gcc:latest

stages:
  - build
  - test
  
job_build:
  stage: build
  script:
    - echo "Building the project"
    - mkdir build
    - cd build
    - cmake ..
    - make
 
  tags:
    - docker
  when: always

job_test:
  stage: test
  script:
    - echo "Running tests"
    - cd build
    - ./tests
 
  tags:
    - docker
  when: always

deploy-job:
  stage: deploy
  script:
    echo "This is Deploy stage"
  
  tags:
    - docker
  when: always
